"use client"

import React from "react";

const PrivacyPolicy = () => {
  const sections = [
    {
      title: "Interpretation and Definitions",
      content: (
        <>
          <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>

          <p>
            <strong>Company</strong> (referred to as either “the Company”,
            “We”, “Us” or “Our” in this Agreement) refers to Digifine.
          </p>

          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </p>

          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>

          <p>
            <strong>Service</strong> refers to the advertisement, website, or
            application.
          </p>

          <p>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </p>

          <p>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </p>

          <p>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service.
          </p>
        </>
      ),
    },

    {
      title: "Program Terms & Conditions",
      content: (
        <div className="space-y-4">
          <p>
            This is a legal binding agreement between the user/student/learner
            of our programs and Digifine stating the terms that govern the use
            of the platform as defined/stated on this page.
          </p>

          <p>
            Upon payment of the Program fees – in part or whole, depending on
            the Program – Digifine shall deliver the terms of use of the Program
            and grant you access to the Program.
          </p>

          <p>
            Owing to certain exceptional circumstances, if Digifine has granted
            you access to a Program pending payment, and Digifine does not
            receive payments within the stipulated time period, Digifine may, at
            its own discretion, withdraw your access to the Program without
            giving any prior notice.
          </p>

          <p>
            In case, admission of the student is canceled on account of
            disciplinary action or violation of Anti Ragging Regulations or
            Substance Abuse or Breach of Code of Conduct or any other Rules &
            Regulations of the Institute. No Refund of fees is permissible.
          </p>

          <p>
            Admission canceled on grounds of failing the eligibility
            verification, then no amount will be refunded.
          </p>

          <p>
            In any other case which is not covered in these rules, the decision
            would be taken by the Management.
          </p>

          <p>
            Admission stands canceled if a student doesn’t report to the
            institute for more than 20 days and no refund of fees is
            permissible.
          </p>

          <p>
            Admission stands canceled if a student fails to pay fees 15 days
            after the given deadline date.
          </p>

          <h3 className="text-xl font-semibold mt-6">
            Cancellation Policy
          </h3>

          <p>
            Admission or registration once taken cannot be cancelled under any
            given circumstances and no refund would be provided.
          </p>
        </div>
      ),
    },

    {
      title: "Collecting and Using Your Personal Data",
      content: (
        <>
          <h3 className="text-xl font-semibold mb-3">
            Types of Data Collected
          </h3>

          <h4 className="font-semibold mb-2">Personal Data</h4>

          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You.
          </p>

          <ul className="list-disc ml-6 mt-4 space-y-2">
            <li>First name and last name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>
              Location details such as your address, city, or country
            </li>
            <li>
              Any other data such as personal preferences, requirements, or
              comments
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-8 mb-3">
            Use of Your Personal Data
          </h3>

          <ul className="list-disc ml-6 space-y-3">
            <li>
              To provide and maintain our Service, including to monitor the
              usage of our Service.
            </li>

            <li>
              To manage Your Account and provide access to functionalities
              available to registered users.
            </li>

            <li>
              For performance of contracts and services purchased through the
              Service.
            </li>

            <li>
              To contact You through email, telephone calls, SMS, or other
              electronic communication.
            </li>

            <li>
              To provide news, special offers and information about similar
              products and services.
            </li>

            <li>
              To manage Your requests submitted to Us.
            </li>

            <li>
              For business transfers including mergers, restructuring,
              acquisition or sale of assets.
            </li>

            <li>
              For data analysis, improving services, marketing and user
              experience.
            </li>
          </ul>
        </>
      ),
    },

    {
      title: "Disclosure of Your Personal Data",
      content: (
        <div className="space-y-4">
          <p>
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required by law or valid requests by public
            authorities.
          </p>

          <p>The Company may disclose Personal Data to:</p>

          <ul className="list-disc ml-6 space-y-2">
            <li>Comply with legal obligations.</li>
            <li>
              Protect and defend the rights or property of the Company.
            </li>
            <li>
              Prevent or investigate possible wrongdoing.
            </li>
            <li>
              Protect personal safety of Users or the public.
            </li>
            <li>
              Protect against legal liability.
            </li>
          </ul>
        </div>
      ),
    },

    {
      title: "Security of Your Personal Data",
      content: (
        <p>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
      ),
    },

    {
      title: "Links to Other Websites",
      content: (
        <p>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party’s site. We strongly advise You to review the Privacy
          Policy of every site You visit.
          <br />
          <br />
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
      ),
    },

    {
      title: "Placement Terms",
      content: (
        <div className="space-y-4">
          <p>
            Digifine Academy offers a Placement Assistance only for selected
            programs. Eligibility for placement assistance is subject to the
            following conditions:
          </p>

          <ul className="list-disc ml-6 space-y-3">
            <li>
              Placement Assistance applies only to programs explicitly marked as
              “Placement Assistance”.
            </li>

            <li>
              Student must maintain minimum 90% attendance throughout the
              eligible program.
            </li>

            <li>
              100% program fees must be paid and cleared before placement
              assistance begins.
            </li>

            <li>
              Student must successfully clear the final assessment conducted by
              Digifine Academy.
            </li>

            <li>
              Student must participate in interviews and recruitment
              opportunities.
            </li>

            <li>
              Job offers cannot be rejected on grounds of salary, location,
              company, designation, or work timings.
            </li>

            <li>
              Student must maintain professional behavior during the course and
              placement process.
            </li>
          </ul>
        </div>
      ),
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-5xl mx-auto">

        <div className="bg-white rounded-3xl shadow-lg p-8 md:p-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Privacy Policy
          </h1>

          <p className="text-gray-600 mb-10 leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You respond
            to our advertisements and tells You about Your privacy rights and
            how the law protects You.
          </p>

          <div className="space-y-10">
            {sections.map((section, index) => (
              <section key={index}>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  {section.title}
                </h2>

                <div className="text-gray-700 leading-8">
                  {section.content}
                </div>
              </section>
            ))}
          </div>


          <section className="mt-12 border-t pt-8">
            <h2 className="text-2xl font-bold mb-3">
              Contact Us
            </h2>

            <p className="text-gray-700">
              If you have any questions about this Privacy Policy, You can
              contact us via email at{" "}
              <a
                href="mailto:admin@digifine.in"
                className="text-blue-600 font-medium hover:underline"
              >
                admin@digifine.in
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;